package com.example.uks.enumeration;

public enum Category {
    API_MANAGMENT,
    CONTENT_MANAGMENT_SYSTEM,
    DATA_SCIENCE,
    DATABASE_AND_STORAGE,
    DEVOPS,
    DOCKER_EXTENSIONS,
    LANGUAGE_AND_FRAMEWORKS,
    INTEGRATION_AND_DELIVERY,
    FRONTEND,
    INTERNET_OF_THINGS,
    MACHINE_LEARNING_AND_AI,
    MESSAGE_QUEUES,
    MENTORING_AND_OBSERVABILITY,
    NETWORKING,
    OPERATING_SYSTEM,
    OBSERVABILITY,
    SECURITY,
    WEB_SERVERS,
    NONE
}
